import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  AntdStyledComponentsProvider,
  StoreProvider,
} from "@/shared/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <AntdStyledComponentsProvider>
            {children}
          </AntdStyledComponentsProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
